import { Prisma, PrismaClient } from "@prisma/client"

export const seedCharacters = async (prisma: PrismaClient) => {
  console.log("start seeding character...")

  const units = await prisma.unit.findMany({
    select: {
      id: true,
      code: true,
    },
  })

  const characters: Prisma.CharacterCreateManyInput[] = [
    {
      unitId: units.find((unit) => unit.code === "vs")?.id ?? null,
      code: "vs_miku",
      name: "初音ミク",
      short: "ミク",
      bgColor: "#33ccbb",
      color: "#ffffff",
      avatarUrl: "/icons/unit_01_icon_01_miku_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "vs")?.id ?? null,
      code: "vs_rin",
      name: "鏡音リン",
      short: "リン",
      bgColor: "#ffcc11",
      color: "#000000",
      avatarUrl: "/icons/unit_01_icon_02_rin_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "vs")?.id ?? null,
      code: "vs_len",
      name: "鏡音レン",
      short: "レン",
      bgColor: "#ffee11",
      color: "#000000",
      avatarUrl: "/icons/unit_01_icon_03_len_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "vs")?.id ?? null,
      code: "vs_luka",
      name: "巡音ルカ",
      short: "ルカ",
      bgColor: "#ffbbcc",
      color: "#000000",
      avatarUrl: "/icons/unit_01_icon_04_luka_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "vs")?.id ?? null,
      code: "vs_meiko",
      name: "MEIKO",
      short: "MEIKO",
      bgColor: "#dd4444",
      color: "#ffffff",
      avatarUrl: "/icons/unit_01_icon_05_meiko_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "vs")?.id ?? null,
      code: "vs_kaito",
      name: "KAITO",
      short: "KAITO",
      bgColor: "#3366cc",
      color: "#ffffff",
      avatarUrl: "/icons/unit_01_icon_06_kaito_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "leoneed")?.id ?? null,
      code: "leoneed_miku",
      name: "初音ミク",
      short: "ミク",
      bgColor: "#4455dd",
      color: "#ffffff",
      avatarUrl: "/icons/unit_02_icon_01_miku_03.png",
    },
    {
      unitId: units.find((unit) => unit.code === "leoneed")?.id ?? null,
      code: "leoneed_rin",
      name: "鏡音リン",
      short: "リン",
      bgColor: "#4455dd",
      color: "#ffffff",
      avatarUrl: "/icons/unit_02_icon_02_rin_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "leoneed")?.id ?? null,
      code: "leoneed_len",
      name: "鏡音レン",
      short: "レン",
      bgColor: "#4455dd",
      color: "#ffffff",
      avatarUrl: "/icons/unit_02_icon_03_len_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "leoneed")?.id ?? null,
      code: "leoneed_luka",
      name: "巡音ルカ",
      short: "ルカ",
      bgColor: "#4455dd",
      color: "#ffffff",
      avatarUrl: "/icons/unit_02_icon_04_luka_03.png",
    },
    {
      unitId: units.find((unit) => unit.code === "leoneed")?.id ?? null,
      code: "leoneed_meiko",
      name: "MEIKO",
      short: "MEIKO",
      bgColor: "#4455dd",
      color: "#ffffff",
      avatarUrl: "/icons/unit_02_icon_05_meiko_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "leoneed")?.id ?? null,
      code: "leoneed_kaito",
      name: "KAITO",
      short: "KAITO",
      bgColor: "#4455dd",
      color: "#ffffff",
      avatarUrl: "/icons/unit_02_icon_06_kaito_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "leoneed")?.id ?? null,
      code: "leoneed_ichica",
      name: "星乃一歌",
      short: "一歌",
      bgColor: "#33aaee",
      color: "#ffffff",
      avatarUrl: "/icons/unit_02_icon_07_ichica_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "leoneed")?.id ?? null,
      code: "leoneed_saki",
      name: "天馬咲希",
      short: "咲希",
      bgColor: "#ffdd44",
      color: "#000000",
      avatarUrl: "/icons/unit_02_icon_08_saki_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "leoneed")?.id ?? null,
      code: "leoneed_honami",
      name: "望月穂波",
      short: "穂波",
      bgColor: "#ee6666",
      color: "#ffffff",
      avatarUrl: "/icons/unit_02_icon_09_honami_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "leoneed")?.id ?? null,
      code: "leoneed_shiho",
      name: "日野森志歩",
      short: "志歩",
      bgColor: "#bbdd22",
      color: "#ffffff",
      avatarUrl: "/icons/unit_02_icon_10_shiho_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "mmj")?.id ?? null,
      code: "mmj_miku",
      name: "初音ミク",
      short: "ミク",
      bgColor: "#88dd44",
      color: "#000000",
      avatarUrl: "/icons/unit_03_icon_01_miku_03.png",
    },
    {
      unitId: units.find((unit) => unit.code === "mmj")?.id ?? null,
      code: "mmj_rin",
      name: "鏡音リン",
      short: "リン",
      bgColor: "#88dd44",
      color: "#000000",
      avatarUrl: "/icons/unit_03_icon_02_rin_03.png",
    },
    {
      unitId: units.find((unit) => unit.code === "mmj")?.id ?? null,
      code: "mmj_len",
      name: "鏡音レン",
      short: "レン",
      bgColor: "#88dd44",
      color: "#000000",
      avatarUrl: "/icons/unit_03_icon_03_len_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "mmj")?.id ?? null,
      code: "mmj_luka",
      name: "巡音ルカ",
      short: "ルカ",
      bgColor: "#88dd44",
      color: "#000000",
      avatarUrl: "/icons/unit_03_icon_04_luka_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "mmj")?.id ?? null,
      code: "mmj_meiko",
      name: "MEIKO",
      short: "MEIKO",
      bgColor: "#88dd44",
      color: "#000000",
      avatarUrl: "/icons/unit_03_icon_05_meiko_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "mmj")?.id ?? null,
      code: "mmj_kaito",
      name: "KAITO",
      short: "KAITO",
      bgColor: "#88dd44",
      color: "#000000",
      avatarUrl: "/icons/unit_03_icon_06_kaito_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "mmj")?.id ?? null,
      code: "mmj_minori",
      name: "花里みのり",
      short: "みのり",
      bgColor: "#ffccaa",
      color: "#000000",
      avatarUrl: "/icons/unit_03_icon_07_minori_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "mmj")?.id ?? null,
      code: "mmj_haruka",
      name: "桐谷遥",
      short: "遥",
      bgColor: "#99ccff",
      color: "#ffffff",
      avatarUrl: "/icons/unit_03_icon_08_haruka_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "mmj")?.id ?? null,
      code: "mmj_airi",
      name: "桃井愛莉",
      short: "愛莉",
      bgColor: "#ffaacc",
      color: "#ffffff",
      avatarUrl: "/icons/unit_03_icon_09_airi_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "mmj")?.id ?? null,
      code: "mmj_shizuku",
      name: "日野森雫",
      short: "雫",
      bgColor: "#99eedd",
      color: "#000000",
      avatarUrl: "/icons/unit_03_icon_10_shizuku_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "vbs")?.id ?? null,
      code: "vbs_miku",
      name: "初音ミク",
      short: "ミク",
      bgColor: "#ee1166",
      color: "#ffffff",
      avatarUrl: "/icons/unit_04_icon_01_miku_03.png",
    },
    {
      unitId: units.find((unit) => unit.code === "vbs")?.id ?? null,
      code: "vbs_rin",
      name: "鏡音リン",
      short: "リン",
      bgColor: "#ee1166",
      color: "#ffffff",
      avatarUrl: "/icons/unit_04_icon_02_rin_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "vbs")?.id ?? null,
      code: "vbs_len",
      name: "鏡音レン",
      short: "レン",
      bgColor: "#ee1166",
      color: "#ffffff",
      avatarUrl: "/icons/unit_04_icon_03_len_03.png",
    },
    {
      unitId: units.find((unit) => unit.code === "vbs")?.id ?? null,
      code: "vbs_luka",
      name: "巡音ルカ",
      short: "ルカ",
      bgColor: "#ee1166",
      color: "#ffffff",
      avatarUrl: "/icons/unit_04_icon_04_luka_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "vbs")?.id ?? null,
      code: "vbs_meiko",
      name: "MEIKO",
      short: "MEIKO",
      bgColor: "#ee1166",
      color: "#ffffff",
      avatarUrl: "/icons/unit_04_icon_05_meiko_03.png",
    },
    {
      unitId: units.find((unit) => unit.code === "vbs")?.id ?? null,
      code: "vbs_kaito",
      name: "KAITO",
      short: "KAITO",
      bgColor: "#ee1166",
      color: "#ffffff",
      avatarUrl: "/icons/unit_04_icon_06_kaito_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "vbs")?.id ?? null,
      code: "vbs_kohane",
      name: "小豆沢こはね",
      short: "こはね",
      bgColor: "#ff6699",
      color: "#ffffff",
      avatarUrl: "/icons/unit_04_icon_07_kohane_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "vbs")?.id ?? null,
      code: "vbs_an",
      name: "白石杏",
      short: "杏",
      bgColor: "#00bbdd",
      color: "#ffffff",
      avatarUrl: "/icons/unit_04_icon_08_an_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "vbs")?.id ?? null,
      code: "vbs_akito",
      name: "東雲彰人",
      short: "彰人",
      bgColor: "#ff7722",
      color: "#ffffff",
      avatarUrl: "/icons/unit_04_icon_09_akito_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "vbs")?.id ?? null,
      code: "vbs_toya",
      name: "青柳冬弥",
      short: "冬弥",
      bgColor: "#0077dd",
      color: "#ffffff",
      avatarUrl: "/icons/unit_04_icon_10_toya_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "ws")?.id ?? null,
      code: "ws_miku",
      name: "初音ミク",
      short: "ミク",
      bgColor: "#ff9900",
      color: "#ffffff",
      avatarUrl: "/icons/unit_05_icon_01_miku_03.png",
    },
    {
      unitId: units.find((unit) => unit.code === "ws")?.id ?? null,
      code: "ws_rin",
      name: "鏡音リン",
      short: "リン",
      bgColor: "#ff9900",
      color: "#ffffff",
      avatarUrl: "/icons/unit_05_icon_02_rin_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "ws")?.id ?? null,
      code: "ws_len",
      name: "鏡音レン",
      short: "レン",
      bgColor: "#ff9900",
      color: "#ffffff",
      avatarUrl: "/icons/unit_05_icon_03_len_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "ws")?.id ?? null,
      code: "ws_luka",
      name: "巡音ルカ",
      short: "ルカ",
      bgColor: "#ff9900",
      color: "#ffffff",
      avatarUrl: "/icons/unit_05_icon_04_luka_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "ws")?.id ?? null,
      code: "ws_meiko",
      name: "MEIKO",
      short: "MEIKO",
      bgColor: "#ff9900",
      color: "#ffffff",
      avatarUrl: "/icons/unit_05_icon_05_meiko_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "ws")?.id ?? null,
      code: "ws_kaito",
      name: "KAITO",
      short: "KAITO",
      bgColor: "#ff9900",
      color: "#ffffff",
      avatarUrl: "/icons/unit_05_icon_06_kaito_03.png",
    },
    {
      unitId: units.find((unit) => unit.code === "ws")?.id ?? null,
      code: "ws_tsukasa",
      name: "天馬司",
      short: "司",
      bgColor: "#ffbb00",
      color: "#ffffff",
      avatarUrl: "/icons/unit_05_icon_07_tsukasa_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "ws")?.id ?? null,
      code: "ws_emu",
      name: "鳳えむ",
      short: "えむ",
      bgColor: "#ff66bb",
      color: "#ffffff",
      avatarUrl: "/icons/unit_05_icon_08_emu_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "ws")?.id ?? null,
      code: "ws_nene",
      name: "草薙寧々",
      short: "寧々",
      bgColor: "#33dd99",
      color: "#ffffff",
      avatarUrl: "/icons/unit_05_icon_09_nene_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "ws")?.id ?? null,
      code: "ws_rui",
      name: "神代類",
      short: "類",
      bgColor: "#bb88ee",
      color: "#ffffff",
      avatarUrl: "/icons/unit_05_icon_10_rui_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "oclock")?.id ?? null,
      code: "oclock_miku",
      name: "初音ミク",
      short: "ミク",
      bgColor: "#884499",
      color: "#ffffff",
      avatarUrl: "/icons/unit_06_icon_01_miku_03.png",
    },
    {
      unitId: units.find((unit) => unit.code === "oclock")?.id ?? null,
      code: "oclock_rin",
      name: "鏡音リン",
      short: "リン",
      bgColor: "#884499",
      color: "#ffffff",
      avatarUrl: "/icons/unit_06_icon_02_rin_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "oclock")?.id ?? null,
      code: "oclock_len",
      name: "鏡音レン",
      short: "レン",
      bgColor: "#884499",
      color: "#ffffff",
      avatarUrl: "/icons/unit_06_icon_03_len_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "oclock")?.id ?? null,
      code: "oclock_luka",
      name: "巡音ルカ",
      short: "ルカ",
      bgColor: "#884499",
      color: "#ffffff",
      avatarUrl: "/icons/unit_06_icon_04_luka_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "oclock")?.id ?? null,
      code: "oclock_meiko",
      name: "MEIKO",
      short: "MEIKO",
      bgColor: "#884499",
      color: "#ffffff",
      avatarUrl: "/icons/unit_06_icon_05_meiko_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "oclock")?.id ?? null,
      code: "oclock_kaito",
      name: "KAITO",
      short: "KAITO",
      bgColor: "#884499",
      color: "#ffffff",
      avatarUrl: "/icons/unit_06_icon_06_kaito_01.png",
    },
    {
      unitId: units.find((unit) => unit.code === "oclock")?.id ?? null,
      code: "oclock_kanade",
      name: "宵崎奏",
      short: "奏",
      bgColor: "#bb6688",
      color: "#ffffff",
      avatarUrl: "/icons/unit_06_icon_07_kanade_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "oclock")?.id ?? null,
      code: "oclock_mafuyu",
      name: "朝比奈まふゆ",
      short: "まふゆ",
      bgColor: "#8888cc",
      color: "#ffffff",
      avatarUrl: "/icons/unit_06_icon_08_mafuyu_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "oclock")?.id ?? null,
      code: "oclock_ena",
      name: "東雲絵名",
      short: "絵名",
      bgColor: "#ccaa88",
      color: "#ffffff",
      avatarUrl: "/icons/unit_06_icon_09_ena_02.png",
    },
    {
      unitId: units.find((unit) => unit.code === "oclock")?.id ?? null,
      code: "oclock_mizuki",
      name: "暁山瑞希",
      short: "瑞希",
      bgColor: "#ddaacc",
      color: "#ffffff",
      avatarUrl: "/icons/unit_06_icon_10_mizuki_02.png",
    },
  ]

  await prisma.character.deleteMany()
  await prisma.character.createMany({
    data: characters.map((item, index) => ({
      ...item,
      priority: index + 1,
    })),
  })
  console.log("success")
}
