@baseUrl = {{$dotenv BASE_URL}}
@sessionToken = {{$dotenv SESSION_TOKEN}}
@bearerToken = {{$dotenv BEARER_TOKEN}}


## Authentication API Endpoints
### Register user
POST {{baseUrl}}/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "avatarUrl": "https://cdn.discordapp.com/avatars/801483150781317150/5d330f4391b903cad471dc7ca1815d69.png",
  "discordId": "801483150781317150",
  "email": "test@test.com",
  "name": "test"
}

### Get current user
GET {{baseUrl}}/users/me
Accept: application/json
Cookie: next-auth.session-token={{sessionToken}};

### Get characters
GET {{baseUrl}}/characters
Accept: application/json

### Get settings
GET {{baseUrl}}/users/settings
Accept: application/json
Cookie: next-auth.session-token={{sessionToken}};

### Create settings
POST {{baseUrl}}/users/settings
Accept: application/json
Cookie: next-auth.session-token={{sessionToken}};

{
  "leaderSheetUrl": "https://docs.google.com/spreadsheets/d/1234567890/edit"
}

### Update settings
PATCH {{baseUrl}}/users/settings
Accept: application/json
Cookie: next-auth.session-token={{sessionToken}};

{
  "leaderSheetUrl": null
}